language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

addons_shortcuts:
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.8', 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.9', 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc5: &gcc5
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-5', 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-6', 'autoconf-archive', 'libgmp-dev' ]


install:
  - export CXX="$COMPILER"
  - $CXX --version
  - autoconf --version
  - git clone https://bitbucket.org/malb/m4ri.git
  - pushd m4ri && autoreconf --install && ./configure && make && sudo make install && popd
  - wget -O boost_1_58_0.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download
  - tar -xjvf boost_1_58_0.tar.bz2
  - pushd boost_1_58_0 && ./bootstrap.sh && sudo ./b2 --with-test --prefix=/usr/local install && popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

script:
  - autoreconf --install
  - ./configure
  - make
  - make check

matrix:
  include:
    - os: linux
      compiler: "gcc-4.8"
      env: COMPILER=g++-4.8
      addons: *gcc48
    - os: linux
      compiler: "gcc-4.9"
      env: COMPILER=g++-4.9
      addons: *gcc49
    - os: linux
      compiler: "gcc-5"
      env: COMPILER=g++-5
      addons: *gcc5
    - os: linux
      compiler: "gcc-6"
      env: COMPILER=g++-6
      addons: *gcc6
