language: cpp
sudo: required
dist: jammy

#compiler:
  #- gcc
  #- clang

addons_shortcuts:
  addons_gcc11: &gcc11
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-11', 'autoconf-archive', 'libgmp-dev' ]


install:
  - export CXX="$COMPILER"
  - $CXX --version
  - autoconf --version
  - wget https://github.com/malb/m4ri/archive/release-20200125.tar.gz
  - tar -xzf release-20200125.tar.gz
  - pushd m4ri-release-20200125/ && autoreconf --install && ./configure --disable-openmp && make && sudo make install && popd
  - export BOOST_VERSION=${BOOST_MAJOR_VERSION}.${BOOST_MINOR_VERSION}.${BOOST_MAINTENANCE_VERSION}
  - export BOOST_DIR=boost_${BOOST_MAJOR_VERSION}_${BOOST_MINOR_VERSION}_${BOOST_MAINTENANCE_VERSION}
  - wget -O ${BOOST_DIR}.tar.bz2 https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/${BOOST_DIR}.tar.bz2/download
  - tar -xjf ${BOOST_DIR}.tar.bz2
  - pushd ${BOOST_DIR} && ./bootstrap.sh && sudo ./b2 --with-test --prefix=/usr/local install > /dev/null 2>&1 && popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib

script:
  - autoreconf --install
  - ./configure
  - make
  - make check

matrix:
  include:
    - os: linux
      compiler: "gcc-11"
      env:
        - COMPILER=g++-11
        - BOOST_MAJOR_VERSION=1
        - BOOST_MINOR_VERSION=80
        - BOOST_MAINTENANCE_VERSION=0
      addons: *gcc11
    - os: osx
      osx_image: xcode11.3
      env:
        - COMPILER=clang++
        - BOOST_MAJOR_VERSION=1
        - BOOST_MINOR_VERSION=80
        - BOOST_MAINTENANCE_VERSION=0
    - os: linux
      compiler: "gcc-11"
      env:
        - COMPILER=g++-11
        - BOOST_MAJOR_VERSION=1
        - BOOST_MINOR_VERSION=81
        - BOOST_MAINTENANCE_VERSION=0
      addons: *gcc11
    - os: osx
      osx_image: xcode11.3
      env:
        - COMPILER=clang++
        - BOOST_MAJOR_VERSION=1
        - BOOST_MINOR_VERSION=81
        - BOOST_MAINTENANCE_VERSION=0
