#!/usr/bin/env python
# 
# @author Alexander Dreyer
# @date 2007-10-19
# Copyright: (c) 2007-2011 by The PolyBoRi Team
"""ipbori -- An interactive shell for the PolyBoRi framework

This starts an interactive python-based shell -- IPython where available --
which imports the PolyBoRi framework.

"""

from optparse import OptionParser
parser = OptionParser()

(opts, args) = parser.parse_args()
polybori_site = "$RELATIVEPYPREFIX"

# Note: $PBORI_SITE is replaced on installation with relative path 
# to the PolyBoRi python site
if polybori_site.startswith('$'):
  polybori_site = "../pyroot"

import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)),
                                polybori_site))

from polybori.frontend import *
polybori_start(globals())

def ipbori_shell(context):
  try:
    try:
      from IPython.frontend.terminal.interactiveshell import \
          TerminalInteractiveShell
      return TerminalInteractiveShell(user_global_ns = context,
                                      display_banner = True)
    except ImportError:
      import IPython.Shell
      return IPython.Shell.start(context)
      
  except:
    # Fallback to plain interactive python
    import code
    sys.ps1 = "In: "
    result = code.InteractiveConsole(context)
    result.mainloop = result.interact
    return result

# Call the available shell
ipbori_shell(globals()).mainloop()

