# File: pyroot/polybori/dynamic/__init__.py
# Automatically generated by PolyBoRi
# This file is just for developing, it should be be installed.
import imp
imp.load_dynamic("polybori.dynamic.PyPolyBoRi", "/home/dreyer/polybori-hg/polybori/build/tmp/dreyer/pb4980/py/polybori/dynamic/PyPolyBoRi.so")
